spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: root
  service:
    port:8080
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
